### ISSUE TITLE
Distinguish regular from urgent updates

### ISSUE THREAD

**Issue by franglais125** [franglais125/apt-update-indicator#6]
It would be nice to inform the user when an update is urgent.
Perhaps use a more obvious icon for instance.

**Comment by franglais125** [comment]
@lucatrv (or anyone else willing to help of course). A small favor to ask.

I've finally implemented this in https://github.com/franglais125/apt-update-indicator/tree/urgency

It is rather simple for now: it simply lists the urgent updates in red, instead of plain white font.
The icon is set to: `software-update-urgent-symbolic`, otherwise to `software-update-available-symbolic`.

1. I'm not sure these two icons are available on Debian Jessie. If they are not, could you point me to alternatives? I've moved to Stretch a few months ago... Perhaps just removing `-symbolic` from the names is enough?
2. Second thing, whenever you have updates, can you run `pkcon -p get-updates` and post the output? Just to make sure that the script is compatible.

Thanks a lot in advance,
Fran

**Comment by franglais125** [comment]
I just improved the styling quite a bit, and reverted the change of icons.
- Even spacing allows me to put the version number in a nice column
- Color for urgent updates

![screenshot from 2017-06-12 15-46-41](https://user-images.githubusercontent.com/19195975/27053339-fe09169c-4f8a-11e7-8682-543255dccee9.png)

**Comment by franglais125** [comment]
I have merged this to master. The only thing I'm waiting for before closing this issue is to know what the output of `pkcon -p get-updates` is in Debian Jessie, to know whether Gnome 3.14 remains compatible.

**Comment by lucatrv** [comment]
Hi, I confirm that it works on Debian Jessie, a part from even spacing, maybe this is due to the output of `pkcon -p get-updates`, here is an example (not a big deal however):

> Transaction:	Getting updates
Status: 	Waiting in queue
Status: 	Starting
Status: 	Loading cache
Percentage:	0
Percentage:	100
Percentage:	0
Percentage:	50
Percentage:	100
Status: 	Querying
Status: 	Finished
Results:
Security     libmwaw-0.3-3-0.3.1-2+deb8u1.amd64 (stable)

The two icons `software-update-urgent-symbolic` and `software-update-available-symbolic` are present in Debian Jessie, and they look very well!

Cheers

**Comment by franglais125** [comment]
Thanks a lot!

I actually reverted the `symbolic` icon thing. Which one do you think is better? I can always revert it back.

**Comment by lucatrv** [comment]
Yes I know that I wrote [this](https://github.com/franglais125/apt-update-indicator/issues/4#issue-202347484)... but now I actually think that the `symbolic` icons look better

**Comment by franglais125** [comment]
Sounds good! Thank you for your feedback. I'm now using the `symbolic` icons.

I just submitted v15 to e.g.o.
